all:
			make -C debugging all
			make -C rawIO11 all
			make -C sofs11 all
			make -C syscalls11 all
			make -C showBlock11 all
			make -C mkfs11 all
			make -C testifuncs11 all
			make -C mount11 all
			make -C fsck11 all

clean:
			make -C debugging clean
			make -C rawIO11 clean
			make -C sofs11 clean
			make -C syscalls11 clean
			make -C showBlock11 clean
			make -C mkfs11 clean
			make -C testifuncs11 clean
			make -C mount11 clean
			make -C fsck11 clean
